/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rodic_aleksa_miberchatapplication_EncryptMessage */

#ifndef _Included_rodic_aleksa_miberchatapplication_EncryptMessage
#define _Included_rodic_aleksa_miberchatapplication_EncryptMessage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rodic_aleksa_miberchatapplication_EncryptMessage
 * Method:    encryptDecrypt
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rodic_aleksa_miberchatapplication_EncryptMessage_encryptDecrypt
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
